### ISSUE TITLE
status update fails to occur

### ISSUE THREAD

**Issue by GochoMugo** [pstadler/battery.js#2]
`Battery.onUpdate(func)` seems to **not** function as expected. The passed function is never called when status of the battery changes.

I have ended up setting up a timer with `setInterval(fn, timeout)` that keeps calling my function.

**Comment by pstadler** [comment]
On which platform/browser?

**Comment by GochoMugo** [comment]
**Browser**: Google chrome Version 39.0.2171.95 (64-bit)
**OS**: Linux Debian Wheezy

**Comment by pstadler** [comment]
Sorry that it took so long. This is now fixed.
